steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/mathsolver/executor-service' 
      - '-f'
      - 'Dockerfile.executor'
      - '.'
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/mathsolver/executor-service'