import os
import shutil
import uuid
import glob
import time
import asyncio
import traceback
import uvicorn
from typing import Optional, Dict, List
from fastapi import FastAPI, UploadFile, File, HTTPException, Form
from pydantic import BaseModel

print("=== STATEFUL EXECUTOR v2 (Fixed Uploads) ===")

try:
    from kernel_manager import PersistentKernel
except Exception as e:
    print(f"FATAL: Failed to import kernel_manager: {e}")
    traceback.print_exc()
    PersistentKernel = None

try:
    from google.cloud import storage
except Exception as e:
    print(f"WARNING: google.cloud.storage not available: {e}")
    storage = None

BUCKET_NAME = os.getenv("GCS_BUCKET_NAME")
STORAGE_BASE = "/tmp/session_data" # Use /tmp for writable space in Docker/Cloud Run
STORAGE_LIMIT_BYTES = 1.5 * 1024 * 1024 * 1024
os.makedirs(STORAGE_BASE, exist_ok=True)

app = FastAPI()

# Stateful: kernels persist across requests
_storage_client = None


def get_gcs_client():
    """Initializes and returns a Google Cloud Storage client, or None if unavailable/local."""
    global _storage_client
    if _storage_client is None and storage is not None:
        try:
            _storage_client = storage.Client()
            print("✅ GCS Storage Client initialized")
        except Exception as e:
            print(f"WARNING: Could not create storage client: {e}")
            return None
    return _storage_client


def get_session_paths(session_id: str):
    """Create and return local directories for a session."""
    base = os.path.join(STORAGE_BASE, session_id)
    uploads = os.path.join(base, "uploads")
    exports = os.path.join(base, "exports")
    os.makedirs(uploads, exist_ok=True)
    os.makedirs(exports, exist_ok=True)
    return base, uploads, exports

# ──────────────────────────────────────────────
# GCS Helpers
# ──────────────────────────────────────────────

def sync_uploads_from_gcs(session_id: str, local_upload_dir: str):
    """Download files from GCS to local so the kernel can access them."""
    client = get_gcs_client()
    if not client or not BUCKET_NAME:
        return

    try:
        bucket = client.bucket(BUCKET_NAME)
        prefix = f"uploads/{session_id}/"
        blobs = list(bucket.list_blobs(prefix=prefix))

        for blob in blobs:
            # Extract filename from the GCS path
            filename = os.path.basename(blob.name)
            if not filename: continue

            local_path = os.path.join(local_upload_dir, filename)
            
            # Only download if it doesn't exist or size is different
            if not os.path.exists(local_path) or os.path.getsize(local_path) != blob.size:
                blob.download_to_filename(local_path)
                print(f"  ↓ Synced from GCS: {filename}")
    except Exception as e:
        print(f"WARNING: Sync from GCS failed: {e}")


def upload_exports_to_gcs(session_id: str, export_dir: str) -> List[Dict]:
    """Upload files generated by the code (exports/) to GCS."""
    client = get_gcs_client()
    if not os.path.exists(export_dir): return []

    files_found = [f for f in glob.glob(f"{export_dir}/**/*", recursive=True) if os.path.isfile(f)]
    exported = []

    for filepath in files_found:
        filename = os.path.basename(filepath)
        run_id = uuid.uuid4().hex[:6]
        gcs_path = f"outputs/{session_id}/{run_id}_{filename}"
        
        if client and BUCKET_NAME:
            try:
                bucket = client.bucket(BUCKET_NAME)
                blob = bucket.blob(gcs_path)
                blob.upload_from_filename(filepath)
                exported.append({"name": filename, "gcs_path": gcs_path, "url": f"https://storage.googleapis.com/{BUCKET_NAME}/{gcs_path}"})
            except Exception as e:
                print(f"Export failed for {filename}: {e}")
        else:
            exported.append({"name": filename, "gcs_path": "local_only"})
            
    return exported

# ──────────────────────────────────────────────
# API Logic
# ──────────────────────────────────────────────

class CodeRequest(BaseModel):
    code: str
    session_id: str
    timeout: int = 120


@app.post("/upload")
async def upload_file(file: UploadFile = File(...), session_id: str = Form(...)):
    """Saves file to LOCAL uploads folder AND GCS bucket."""
    if not file.filename:
        raise HTTPException(status_code=400, detail="No filename provided")

    session_root, upload_dir, _ = get_session_paths(session_id)
    local_path = os.path.join(upload_dir, file.filename)

    # 1. Save Locally
    try:
        content = await file.read()
        with open(local_path, "wb") as f:
            f.write(content)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to save locally: {e}")

    # 2. Upload to GCS (Background-ish)
    client = get_gcs_client()
    gcs_status = "skipped"
    if client and BUCKET_NAME:
        try:
            bucket = client.bucket(BUCKET_NAME)
            blob = bucket.blob(f"uploads/{session_id}/{file.filename}")
            blob.upload_from_filename(local_path)
            gcs_status = "success"
        except Exception as e:
            print(f"GCS Upload Error: {e}")
            gcs_status = f"error: {e}"

    return {
        "status": "success",
        "filename": file.filename,
        "local_path": local_path,
        "gcs": gcs_status
    }


@app.post("/execute")
async def execute(request: CodeRequest):
    session_root, upload_dir, export_dir = get_session_paths(request.session_id)

    # 1. Sync files from GCS (in case they were uploaded to a different instance)
    sync_uploads_from_gcs(request.session_id, upload_dir)

    # 2. Prepare Kernel
    if request.session_id not in kernels:
        if PersistentKernel is None:
            raise HTTPException(status_code=500, detail="Kernel manager unavailable")
        kernels[request.session_id] = PersistentKernel()

    kernel = kernels[request.session_id]

    # 3. Setup environment inside the kernel
    # We set the CWD to session_root and add 'uploads' to the path
    setup_code = f"""
import os, sys
os.chdir(r'{os.path.abspath(session_root)}')
if 'uploads' not in sys.path: sys.path.append(r'{os.path.abspath(upload_dir)}')
"""
    kernel.execute_code(setup_code)

    # 4. Clear old exports
    for f in os.listdir(export_dir):
        shutil.rmtree(os.path.join(export_dir, f), ignore_errors=True) if os.path.isdir(os.path.join(export_dir, f)) else os.unlink(os.path.join(export_dir, f))

    # 5. Run User Code
    loop = asyncio.get_running_loop()
    try:
        result = await asyncio.wait_for(
            loop.run_in_executor(None, kernel.execute_code, request.code),
            timeout=request.timeout
        )
        
        # 6. Export files
        result["files"] = upload_exports_to_gcs(request.session_id, export_dir)
        return result

    except asyncio.TimeoutError:
        return {"status": "error", "error": "Timeout"}
    except Exception as e:
        return {"status": "error", "error": str(e)}

@app.on_event("startup")
async def startup():
    asyncio.create_task(cleanup_old_sessions())

async def cleanup_old_sessions():
    while True:
        await asyncio.sleep(3600)
        # Add logic to check os.path.getmtime and remove stale kernels/dirs

if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8080))
    uvicorn.run(app, host="0.0.0.0", port=port)